### ISSUE TITLE
Using SNN graph for clustering

### ISSUE THREAD

**Issue by piplus2** [MaksimEkin/COVID19-Literature-Clustering#4]
Great work!

Instead of k-means, shared nearest neighbour graph can give more accurate clustering results.
One idea is to use SNN graph and leidenalg to determine the clusters.

here a repo for SNN

https://github.com/amararyal/Python-Shared-Nearest-Neighbor-Clustering-SNN-/blob/master/PythonSNN.py

**Comment by MaksimEkin** [comment]
Thank you very much for your feedback! This is a very good idea. We will look into how we can use this. Thank you for the resource as well.
